---
title: Použití výjimek – C# Průvodce programováním
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], about exceptions
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
ms.openlocfilehash: 4012027dc1a9bd2543d0a4195360e5f7e0586fe1
ms.sourcegitcommit: 5f236cd78cf09593c8945a7d753e0850e96a0b80
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 01/07/2020
ms.locfileid: "75705259"
---
# <a name="using-exceptions-c-programming-guide"></a><span data-ttu-id="f0801-102">Použití výjimek (Průvodce programováním v C#)</span><span class="sxs-lookup"><span data-stu-id="f0801-102">Using Exceptions (C# Programming Guide)</span></span>
<span data-ttu-id="f0801-103">V C#systému jsou chyby v programu v době běhu šířeny prostřednictvím programu pomocí mechanismu nazývaného výjimky.</span><span class="sxs-lookup"><span data-stu-id="f0801-103">In C#, errors in the program at run time are propagated through the program by using a mechanism called exceptions.</span></span> <span data-ttu-id="f0801-104">Výjimky jsou vyvolány kódem, který zaznamená chybu a zachycena kódem, který může chybu opravit.</span><span class="sxs-lookup"><span data-stu-id="f0801-104">Exceptions are thrown by code that encounters an error and caught by code that can correct the error.</span></span> <span data-ttu-id="f0801-105">Výjimky mohou být vyvolány .NET Framework Common Language Runtime (CLR) nebo pomocí kódu v programu.</span><span class="sxs-lookup"><span data-stu-id="f0801-105">Exceptions can be thrown by the .NET Framework common language runtime (CLR) or by code in a program.</span></span> <span data-ttu-id="f0801-106">Jakmile je vyvolána výjimka, rozšíří zásobník volání, dokud není nalezen příkaz `catch` pro výjimku.</span><span class="sxs-lookup"><span data-stu-id="f0801-106">Once an exception is thrown, it propagates up the call stack until a `catch` statement for the exception is found.</span></span> <span data-ttu-id="f0801-107">Nezachycené výjimky jsou zpracovávány pomocí obecné obslužné rutiny výjimky poskytované systémem, který zobrazuje dialogové okno.</span><span class="sxs-lookup"><span data-stu-id="f0801-107">Uncaught exceptions are handled by a generic exception handler provided by the system that displays a dialog box.</span></span>  
  
 <span data-ttu-id="f0801-108">Výjimky jsou reprezentovány třídami odvozenými z <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="f0801-108">Exceptions are represented by classes derived from <xref:System.Exception>.</span></span> <span data-ttu-id="f0801-109">Tato třída identifikuje typ výjimky a obsahuje vlastnosti, které obsahují podrobnosti o výjimce.</span><span class="sxs-lookup"><span data-stu-id="f0801-109">This class identifies the type of exception and contains properties that have details about the exception.</span></span> <span data-ttu-id="f0801-110">Vyvolání výjimky zahrnuje vytvoření instance třídy odvozené od výjimky, volitelně konfiguraci vlastností výjimky a následnou vyvolání objektu pomocí klíčového slova `throw`.</span><span class="sxs-lookup"><span data-stu-id="f0801-110">Throwing an exception involves creating an instance of an exception-derived class, optionally configuring properties of the exception, and then throwing the object by using the `throw` keyword.</span></span> <span data-ttu-id="f0801-111">Příklad:</span><span class="sxs-lookup"><span data-stu-id="f0801-111">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#1](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#1)]  
  
 <span data-ttu-id="f0801-112">Po vyvolání výjimky modul runtime zkontroluje aktuální příkaz a zjistí, zda je v rámci `try`ho bloku.</span><span class="sxs-lookup"><span data-stu-id="f0801-112">After an exception is thrown, the runtime checks the current statement to see whether it is within a `try` block.</span></span> <span data-ttu-id="f0801-113">Pokud je, jsou zkontrolovány všechny `catch` bloky přidružené k bloku `try`, aby bylo vidět, zda mohou zachytit výjimku.</span><span class="sxs-lookup"><span data-stu-id="f0801-113">If it is, any `catch` blocks associated with the `try` block are checked to see whether they can catch the exception.</span></span> <span data-ttu-id="f0801-114">bloky `Catch` obvykle určují typy výjimek; Pokud typ `catch` bloku je stejného typu jako výjimka nebo základní třída výjimky, může blok `catch` zpracovat metodu.</span><span class="sxs-lookup"><span data-stu-id="f0801-114">`Catch` blocks typically specify exception types; if the type of the `catch` block is the same type as the exception, or a base class of the exception, the `catch` block can handle the method.</span></span> <span data-ttu-id="f0801-115">Příklad:</span><span class="sxs-lookup"><span data-stu-id="f0801-115">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#2](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#2)]  
  
 <span data-ttu-id="f0801-116">Pokud příkaz, který vyvolá výjimku, není v rámci `try` bloku nebo pokud blok `try`, který ho obklopuje, nemá odpovídající blok `catch`, modul runtime zkontroluje volající metodu pro příkaz `try` a `catch` bloky.</span><span class="sxs-lookup"><span data-stu-id="f0801-116">If the statement that throws an exception is not within a `try` block or if the `try` block that encloses it has no matching `catch` block, the runtime checks the calling method for a `try` statement and `catch` blocks.</span></span> <span data-ttu-id="f0801-117">Modul runtime pokračuje v zásobníku volání a hledá kompatibilní blok `catch`.</span><span class="sxs-lookup"><span data-stu-id="f0801-117">The runtime continues up the calling stack, searching for a compatible `catch` block.</span></span> <span data-ttu-id="f0801-118">Po nalezení a spuštění bloku `catch` je ovládací prvek předán dalšímu příkazu po tomto bloku `catch`.</span><span class="sxs-lookup"><span data-stu-id="f0801-118">After the `catch` block is found and executed, control is passed to the next statement after that `catch` block.</span></span>  
  
 <span data-ttu-id="f0801-119">Příkaz `try` může obsahovat více než jeden `catch` blok.</span><span class="sxs-lookup"><span data-stu-id="f0801-119">A `try` statement can contain more than one `catch` block.</span></span> <span data-ttu-id="f0801-120">První příkaz `catch`, který může zpracovat výjimku, je proveden; všechny následující příkazy `catch`, i když jsou kompatibilní, se ignorují.</span><span class="sxs-lookup"><span data-stu-id="f0801-120">The first `catch` statement that can handle the exception is executed; any following `catch` statements, even if they are compatible, are ignored.</span></span> <span data-ttu-id="f0801-121">Proto by bloky catch měly být vždy řazeny z nejvíce specifického (nebo nejvíce odvozeného) na nejméně konkrétní.</span><span class="sxs-lookup"><span data-stu-id="f0801-121">Therefore, catch blocks should always be ordered from most specific (or most-derived) to least specific.</span></span> <span data-ttu-id="f0801-122">Příklad:</span><span class="sxs-lookup"><span data-stu-id="f0801-122">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#3](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#3)]  
  
 <span data-ttu-id="f0801-123">Před spuštěním bloku `catch` modul runtime vyhledá bloky `finally`.</span><span class="sxs-lookup"><span data-stu-id="f0801-123">Before the `catch` block is executed, the runtime checks for `finally` blocks.</span></span> <span data-ttu-id="f0801-124">`Finally` bloky umožňují programátorovi vyčistit jakýkoli nejednoznačný stav, který by mohl zůstat z přerušeného `try` bloku, nebo uvolnit jakékoli externí prostředky (například grafické popisovače, databázová připojení nebo datové proudy souborů) bez čekání na uvolnění paměti systémem uvolňování paměti v modulu runtime.</span><span class="sxs-lookup"><span data-stu-id="f0801-124">`Finally` blocks enable the programmer to clean up any ambiguous state that could be left over from an aborted `try` block, or to release any external resources (such as graphics handles, database connections or file streams) without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="f0801-125">Příklad:</span><span class="sxs-lookup"><span data-stu-id="f0801-125">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#4](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#4)]  
  
 <span data-ttu-id="f0801-126">Pokud `WriteByte()` vyvolala výjimku, kód v druhém bloku `try`, který se pokusí znovu otevřít soubor, by nebyl úspěšný, pokud `file.Close()` není volán a soubor by zůstal uzamčen.</span><span class="sxs-lookup"><span data-stu-id="f0801-126">If `WriteByte()` threw an exception, the code in the second `try` block that tries to reopen the file would fail if `file.Close()` is not called, and the file would remain locked.</span></span> <span data-ttu-id="f0801-127">Vzhledem k tomu, že `finally` bloky jsou spouštěny i v případě, že dojde k výjimce, bloku `finally` v předchozím příkladu umožní, aby se soubor správně zavřel a pomáhá se vyhnout chybě.</span><span class="sxs-lookup"><span data-stu-id="f0801-127">Because `finally` blocks are executed even if an exception is thrown, the `finally` block in the previous example allows for the file to be closed correctly and helps avoid an error.</span></span>  
  
 <span data-ttu-id="f0801-128">Pokud v zásobníku volání není po vyvolání výjimky nalezen žádný kompatibilní blok `catch`, dojde k jedné ze tří akcí:</span><span class="sxs-lookup"><span data-stu-id="f0801-128">If no compatible `catch` block is found on the call stack after an exception is thrown, one of three things occurs:</span></span>  
  
- <span data-ttu-id="f0801-129">Pokud je výjimka v finalizační metodě, finalizační metoda je přerušena a základní finalizační metoda, pokud existuje, je volána.</span><span class="sxs-lookup"><span data-stu-id="f0801-129">If the exception is within a finalizer, the finalizer is aborted and the base finalizer, if any, is called.</span></span>  
  
- <span data-ttu-id="f0801-130">Pokud zásobník volání obsahuje statický konstruktor nebo inicializátor statických polí, je vyvolána <xref:System.TypeInitializationException>, s původní výjimkou přiřazenou vlastnosti <xref:System.Exception.InnerException%2A> nové výjimky.</span><span class="sxs-lookup"><span data-stu-id="f0801-130">If the call stack contains a static constructor, or a static field initializer, a <xref:System.TypeInitializationException> is thrown, with the original exception assigned to the <xref:System.Exception.InnerException%2A> property of the new exception.</span></span>  
  
- <span data-ttu-id="f0801-131">Pokud je dosaženo začátku vlákna, vlákno je ukončeno.</span><span class="sxs-lookup"><span data-stu-id="f0801-131">If the start of the thread is reached, the thread is terminated.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="f0801-132">Viz také:</span><span class="sxs-lookup"><span data-stu-id="f0801-132">See also</span></span>

- [<span data-ttu-id="f0801-133">Průvodce programováním v jazyce C#</span><span class="sxs-lookup"><span data-stu-id="f0801-133">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="f0801-134">Výjimky a jejich zpracování</span><span class="sxs-lookup"><span data-stu-id="f0801-134">Exceptions and Exception Handling</span></span>](./index.md)
