---
ms.openlocfilehash: 52406f1e4ea4eda417909e52cf6529631cb0ae33
ms.sourcegitcommit: e02d17b2cf9c1258dadda4810a5e6072a0089aee
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 07/01/2020
ms.locfileid: "85619963"
---
### <a name="change-in-behavior-for-taskwaitall-methods-with-time-out-arguments"></a><span data-ttu-id="4052d-101">Změna chování pro metody Task. WaitAll s argumenty časového limitu</span><span class="sxs-lookup"><span data-stu-id="4052d-101">Change in behavior for Task.WaitAll methods with time-out arguments</span></span>

#### <a name="details"></a><span data-ttu-id="4052d-102">Podrobnosti</span><span class="sxs-lookup"><span data-stu-id="4052d-102">Details</span></span>

<span data-ttu-id="4052d-103"><xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType>chování bylo v souladu s .NET Framework 4.5.In .NET Framework 4, tyto metody se chovají nekonzistentně.</span><span class="sxs-lookup"><span data-stu-id="4052d-103"><xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> behavior was made more consistent in .NET Framework 4.5.In the .NET Framework 4, these methods behaved inconsistently.</span></span> <span data-ttu-id="4052d-104">Po vypršení časového limitu, pokud před voláním metody byla dokončena nebo zrušena jedna nebo více úloh, metoda vyvolala <xref:System.AggregateException?displayProperty=fullName> výjimku.</span><span class="sxs-lookup"><span data-stu-id="4052d-104">When the time-out expired, if one or more tasks were completed or canceled before the method call, the method threw an <xref:System.AggregateException?displayProperty=fullName> exception.</span></span> <span data-ttu-id="4052d-105">Po vypršení časového limitu, pokud nebyly dokončeny nebo zrušeny žádné úkoly před voláním metody, ale jedna nebo více úloh zadal tyto stavy po volání metody, metoda vrátila hodnotu false.</span><span class="sxs-lookup"><span data-stu-id="4052d-105">When the time-out expired, if no tasks were completed or canceled before the method call, but one or more tasks entered these states after the method call, the method returned false.</span></span><br/><br/><span data-ttu-id="4052d-106">V .NET Framework 4,5 Tato přetížení metody nyní vrací hodnotu false, pokud některé úlohy stále běží, když vypršel časový limit, a vyvolávají <xref:System.AggregateException?displayProperty=fullName> výjimku pouze v případě, že vstupní úkol byl zrušen (bez ohledu na to, zda byl dříve nebo po volání metody) a zda stále nejsou spuštěny žádné další úlohy.</span><span class="sxs-lookup"><span data-stu-id="4052d-106">In the .NET Framework 4.5, these method overloads now return false if any tasks are still running when the time-out interval expired, and they throw an <xref:System.AggregateException?displayProperty=fullName> exception only if an input task was cancelled (regardless of whether it was before or after the method call) and no other tasks are still running.</span></span>

#### <a name="suggestion"></a><span data-ttu-id="4052d-107">Návrh</span><span class="sxs-lookup"><span data-stu-id="4052d-107">Suggestion</span></span>

<span data-ttu-id="4052d-108">Pokud <xref:System.AggregateException?displayProperty=fullName> byla zachycena jako způsob detekce úlohy, která byla zrušena před <xref:System.Threading.Tasks.Task.WaitAll%2A> vyvoláním volání, měl by tento kód místo toho provádět stejné zjišťování prostřednictvím <xref:System.Threading.Tasks.Task.IsCanceled%2A> vlastnosti (například:. Any (t = &gt; t. uncanceled)), protože .NET Framework 4,6 bude v takovém případě vyvolána pouze v případě, že všechny očekávané úkoly byly dokončeny před časovým limitem.</span><span class="sxs-lookup"><span data-stu-id="4052d-108">If an <xref:System.AggregateException?displayProperty=fullName> was being caught as a means of detecting a task that was cancelled prior to the <xref:System.Threading.Tasks.Task.WaitAll%2A> call being invoked, that code should instead do the same detection via the  <xref:System.Threading.Tasks.Task.IsCanceled%2A> property (for example: .Any(t =&gt; t.IsCanceled)) since .NET Framework 4.6 will only throw in that case if all awaited tasks are completed prior to the timeout.</span></span>

| <span data-ttu-id="4052d-109">Name</span><span class="sxs-lookup"><span data-stu-id="4052d-109">Name</span></span>    | <span data-ttu-id="4052d-110">Hodnota</span><span class="sxs-lookup"><span data-stu-id="4052d-110">Value</span></span>       |
|:--------|:------------|
| <span data-ttu-id="4052d-111">Rozsah</span><span class="sxs-lookup"><span data-stu-id="4052d-111">Scope</span></span>   |<span data-ttu-id="4052d-112">Vedlejší</span><span class="sxs-lookup"><span data-stu-id="4052d-112">Minor</span></span>|
|<span data-ttu-id="4052d-113">Verze</span><span class="sxs-lookup"><span data-stu-id="4052d-113">Version</span></span>|<span data-ttu-id="4052d-114">4.5</span><span class="sxs-lookup"><span data-stu-id="4052d-114">4.5</span></span>|
|<span data-ttu-id="4052d-115">Typ</span><span class="sxs-lookup"><span data-stu-id="4052d-115">Type</span></span>|<span data-ttu-id="4052d-116">Modul runtime</span><span class="sxs-lookup"><span data-stu-id="4052d-116">Runtime</span></span>

#### <a name="affected-apis"></a><span data-ttu-id="4052d-117">Ovlivněná rozhraní API</span><span class="sxs-lookup"><span data-stu-id="4052d-117">Affected APIs</span></span>

-<xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32,System.Threading.CancellationToken)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.TimeSpan)?displayProperty=nameWithType></li></ul>|
